---

all:

  hosts:

    controller:
      ansible_host: localhost
      ansible_connection: local
    kube1:
      ansible_host: 192.168.7.3
    kube2:
      ansible_host: 192.168.7.10
    kube3:
      ansible_host: 192.168.7.11

  vars:

    ansible_python_interpreter: /usr/bin/python3
    pip_package: python3-pip
    pip_executable: pip3

  children:

    k8s:

      hosts:
        kube1:
        kube2:
        kube3:
      vars:
        ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
        ansible_ssh_user: vagrant

      children:

        k8s_masters:
          hosts:
            kube1:
          vars:
            kubernetes_role: master

        k8s_nodes:
          hosts:
            kube2:
            kube3:
          vars:
            kubernetes_role: node

      # # ansible_host: services-node-1
      # ansible_host: 172.16.1.101
      # ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
      # ansible_ssh_user: vagrant

