---
roles:
  - name: geerlingguy.security
  - name: geerlingguy.swap
  - name: geerlingguy.docker
  - name: geerlingguy.kubernetes
  - name: chusiang.helloworld
    cms: git
    src: https://github.com/chusiang/helloworld.ansible.role.git
    version: origin/master
